global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "inference"
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "exporter"
    static_configs:
      - targets: ["localhost:8001"]